name: ❓ Support Question
description: All other questions about using the library
labels: [help wanted]

body:
  - type: input
    id: affected-versions
    attributes:
      label: Fakturoid PHP lib version(s) affected
      placeholder: x.y.z
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the problem
    validations:
      required: true
