# Based on https://github.com/actions/starter-workflows/blob/3be3c5deec708a2becaca71ec12dce81ae3d6080/ci/php.yml
name: Verify
on:
  push:
  pull_request:
    branches: [ $default-branch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        # Required by phpunit.
        php-version: 7.4
        extensions: curl, json
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Run tests
      run: composer test
